title: "Letro"
description: "Like email, but end-to-end encrypted, spam-free, phishing-free and works without the Internet too."
baseurl: /en

markdown: kramdown
liquid:
  error_mode: strict
  strict_filters: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
include:
  - ".well-known"
  - "es"
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .idea
  - README.md
  - es
  - .well-known
  - index.html

# Theme settings
remote_theme: "pmarsceill/just-the-docs@v0.7.0"
logo: "/assets/logo.png"
search_enabled: false
aux_links:
  "GitHub repo": "https://github.com/CheLetro/website-root"
  "Relaycorp": "https://relaycorp.tech"
heading_anchors: true
